name: Windows-RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setting Up
      run: |
        echo "Starting..."
    - name: Setup Tmate
      uses: mxschmitt/action-tmate@v3
